name: 'snowflake_tpch_demo'
version: '1.0.0'



profile: 'snowflake_tpch_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_tpch_demo:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table