[project]
name = "snowflake-dbt-assessment"
version = "0.1.0"
description = ""
authors = [
    {name = "bassel27",email = "bassel_sabour@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-snowflake (>=1.10.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
